### PR TITLE
Implemented book chapter template option

### PR DESCRIPTION
**Pull request by myucekul**

### CODE REVIEW

**Comment by everreau** [comment]
this template looks fine but should it be used somewhere in the code?

**Comment by myucekul** [comment]
> this template looks fine but should it be used somewhere in the code?

Good call - please see the updates to logic.py

**Comment by everreau** [comment]
oh, I'm sorry I didn't think of this earlier but I think it would be a good idea to make this a journal setting. add to install/settings.json you can then access this setting the same way that "enabled" is accessed.  Keeps ezid plugin from depending on eschol.

**Comment by myucekul** [comment]
> 

I agree, Esther. ezid settings are already at multiple places adding one in j2e plugin doesn't sound great. Would you please add your suggestion to the trello card and get Justin's take on that. 
https://trello.com/c/skwxJ8Yw

**Comment by everreau** [comment]
This looks good.  Two small clean ups, you can remove the JournalUnit import and there appears to still be a debug print message.

**Comment by myucekul** [comment]
> This looks good. Two small clean ups, you can remove the JournalUnit import and there appears to still be a debug print message.

Thanks Esther. Import is removed and print is commented out.

**Pull request merged**
