### PR TITLE
Check for empty license url

### PR DESCRIPTION
**Pull request by myucekul**
Added check for empty license URL before including the license information in crossref xml.

### CODE REVIEW

**Review by bibliotechy — APPROVED** [review]
Not a blocker, and approved, but ideally, these kinds of checks happen in the view, not the template, as it is much easier to write a test for function called in a view than it is to test in a template. But in this case, as that's how all of our tests are already set up, I think this makes sense. Just noting it future good practice.

**Comment by everreau** [comment]
There aren't tests written for it but you can see in logic we do a similar validation of orcid urls in the code.

**Comment by myucekul** [comment]
Incorporated the suggestions.

**Review by bibliotechy — APPROVED** [review]
👍

**Pull request merged**
