### PR TITLE
WIP: Add license info Pubd1170

### PR DESCRIPTION
**Pull request by myucekul**

### CODE REVIEW

**Comment by everreau** [comment]
The tests are currently failing but it looks like it's due to inadvertent changes to the whitespace in the template. Unfortunately, I don't immediately know how to fix the tests (other than just adding the new whitespace) because I'm using mock.

It would be good to add a test that tests this functionality.

**Comment by myucekul** [comment]
> The tests are currently failing but it looks like it's due to inadvertent changes to the whitespace in the template. Unfortunately, I don't immediately know how to fix the tests (other than just adding the new whitespace) because I'm using mock.
> 
> It would be good to add a test that tests this functionality.

Thanks for writing unit tests, Esther. I tried running those on Janeway dev. Please share instructions for executing the tests. 
> python manage.py test ezid
Creating test database for alias 'default'...
Got an error creating the test database: (1044, "Access denied for user 'janewaydba'@'%' to database 'test_janeway'")

**Comment by everreau** [comment]
In my PR from yesterday I added documentation to the README about running tests.  They have to be run in a development environment or at least an environment where the db user can create and destroy a new database.  This is to create a consistent environment to test against.

**Comment by myucekul** [comment]
Closing this. I'll create a new PR.

**Pull request closed without merging**
